# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: xenial  # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:

env:
  global:
    - MOVEIT_CI_TRAVIS_TIMEOUT=85  # Travis grants us 90 min, but we add a safety margin of 5 min
    - ROS_DISTRO=dashing
    - ROS_REPO=ros-testing
    - UPSTREAM_WORKSPACE=moveit2.repos
    # moveit_ros_perception: mesh_filter_test fails due to broken Mesa OpenGL
    - TEST_BLACKLIST="moveit_ros_perception"
    - CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls"
    - WARNINGS_OK=false
  matrix:
    # TODO(henningkayser): Enable ament_lint once all packages are ported
    - TEST="clang-format"
    - ROS_DISTRO=dashing

# TODO(mlautman): Enable once franka_ikfast_plugin and panda_ikfast_plugin are available
# matrix: # Add a separate config to the matrix, using clang as compiler
  # include:
    # # add a config to the matrix using clang as compiler and also test ikfast plugin creation
    # - compiler: clang
      # env: ROS_REPO=ros
           # BEFORE_DOCKER_SCRIPT="source moveit_kinematics/test/test_ikfast_plugins.sh"
           # CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-unused-parameter -Wno-unused-function -Wno-overloaded-virtual"

before_script:
  - git clone -q -b ros2 --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
